//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnds.RoboPrinter.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontEnds.RoboPrinter.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accedi.
        /// </summary>
        public static string Accedi {
            get {
                return ResourceManager.GetString("Accedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiungi Punto di Svincolo.
        /// </summary>
        public static string AggiungiSvincolo {
            get {
                return ResourceManager.GetString("AggiungiSvincolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Applica.
        /// </summary>
        public static string Applica {
            get {
                return ResourceManager.GetString("Applica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Applica Filtri.
        /// </summary>
        public static string ApplicaFiltri {
            get {
                return ResourceManager.GetString("ApplicaFiltri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assorbimento Asse J1.
        /// </summary>
        public static string AssorbimentoAsseJ1 {
            get {
                return ResourceManager.GetString("AssorbimentoAsseJ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assorbimento Asse J2.
        /// </summary>
        public static string AssorbimentoAsseJ2 {
            get {
                return ResourceManager.GetString("AssorbimentoAsseJ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assorbimento Asse J3.
        /// </summary>
        public static string AssorbimentoAsseJ3 {
            get {
                return ResourceManager.GetString("AssorbimentoAsseJ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assorbimento Asse J4.
        /// </summary>
        public static string AssorbimentoAsseJ4 {
            get {
                return ResourceManager.GetString("AssorbimentoAsseJ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assorbimento Asse J5.
        /// </summary>
        public static string AssorbimentoAsseJ5 {
            get {
                return ResourceManager.GetString("AssorbimentoAsseJ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Assorbimento Asse J6.
        /// </summary>
        public static string AssorbimentoAsseJ6 {
            get {
                return ResourceManager.GetString("AssorbimentoAsseJ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autoapplicazione.
        /// </summary>
        public static string Autoapplicazione {
            get {
                return ResourceManager.GetString("Autoapplicazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avvia Ciclo.
        /// </summary>
        public static string AvviaCiclo {
            get {
                return ResourceManager.GetString("AvviaCiclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avvia Ciclo Continuo.
        /// </summary>
        public static string AvviaCicloContinuo {
            get {
                return ResourceManager.GetString("AvviaCicloContinuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avvia Ciclo Singolo.
        /// </summary>
        public static string AvviaCicloSingolo {
            get {
                return ResourceManager.GetString("AvviaCicloSingolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Azzera Filtri.
        /// </summary>
        public static string AzzeraFiltri {
            get {
                return ResourceManager.GetString("AzzeraFiltri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CancellaTutto.
        /// </summary>
        public static string CancellaTutto {
            get {
                return ResourceManager.GetString("CancellaTutto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica.
        /// </summary>
        public static string Carica {
            get {
                return ResourceManager.GetString("Carica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sicuro di voler spegnere il sistema?.
        /// </summary>
        public static string ConfermaSpegnimento {
            get {
                return ResourceManager.GetString("ConfermaSpegnimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contenuto.
        /// </summary>
        public static string Contenuto {
            get {
                return ResourceManager.GetString("Contenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Da.
        /// </summary>
        public static string Da {
            get {
                return ResourceManager.GetString("Da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione.
        /// </summary>
        public static string Descrizione {
            get {
                return ResourceManager.GetString("Descrizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Diagnostica.
        /// </summary>
        public static string Diagnostica {
            get {
                return ResourceManager.GetString("Diagnostica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duplica.
        /// </summary>
        public static string Duplica {
            get {
                return ResourceManager.GetString("Duplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ELIMINA.
        /// </summary>
        public static string Elimina {
            get {
                return ResourceManager.GetString("Elimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Etichette.
        /// </summary>
        public static string Etichette {
            get {
                return ResourceManager.GetString("Etichette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Funzioni Manuali.
        /// </summary>
        public static string FunzioniManuali {
            get {
                return ResourceManager.GetString("FunzioniManuali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Funzioni Manuali e Diagnostica.
        /// </summary>
        public static string FunzioniManualieDiagnostica {
            get {
                return ResourceManager.GetString("FunzioniManualieDiagnostica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I/O Digitali.
        /// </summary>
        public static string I_ODigitali {
            get {
                return ResourceManager.GetString("I/ODigitali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare un prodotto da clonare.
        /// </summary>
        public static string IdProdottoRichiesto {
            get {
                return ResourceManager.GetString("IdProdottoRichiesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        public static string Impostazioni {
            get {
                return ResourceManager.GetString("Impostazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Matricola.
        /// </summary>
        public static string Matricola {
            get {
                return ResourceManager.GetString("Matricola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità Corrente.
        /// </summary>
        public static string ModalitaCorrente {
            get {
                return ResourceManager.GetString("ModalitaCorrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità Impulsiva.
        /// </summary>
        public static string ModalitaImpulsiva {
            get {
                return ResourceManager.GetString("ModalitaImpulsiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità Operativa.
        /// </summary>
        public static string ModalitaOperativa {
            get {
                return ResourceManager.GetString("ModalitaOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mostra Filtri.
        /// </summary>
        public static string MostraFiltri {
            get {
                return ResourceManager.GetString("MostraFiltri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nascondi Filtri.
        /// </summary>
        public static string NascondiFiltri {
            get {
                return ResourceManager.GetString("NascondiFiltri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome Prodotto.
        /// </summary>
        public static string Nome_Prodotto {
            get {
                return ResourceManager.GetString("Nome Prodotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il nome del prodotto è obbligatorio.
        /// </summary>
        public static string NomeProdottoRichiesto {
            get {
                return ResourceManager.GetString("NomeProdottoRichiesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovo Prodotto.
        /// </summary>
        public static string Nuovo_Prodotto {
            get {
                return ResourceManager.GetString("Nuovo Prodotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovo Prodotto.
        /// </summary>
        public static string NuovoProdotto {
            get {
                return ResourceManager.GetString("NuovoProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Orario di applicazione.
        /// </summary>
        public static string OrarioApplicazione {
            get {
                return ResourceManager.GetString("OrarioApplicazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Orario di prelievo.
        /// </summary>
        public static string OrarioPrelievo {
            get {
                return ResourceManager.GetString("OrarioPrelievo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La password è obbligatoria.
        /// </summary>
        public static string PasswordRichiesta {
            get {
                return ResourceManager.GetString("PasswordRichiesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percorso.
        /// </summary>
        public static string Percorso {
            get {
                return ResourceManager.GetString("Percorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pneumatica - Soffiatore.
        /// </summary>
        public static string PneumaticaSoffiatore {
            get {
                return ResourceManager.GetString("PneumaticaSoffiatore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pneumatica - Vuoto.
        /// </summary>
        public static string PneumaticaVuoto {
            get {
                return ResourceManager.GetString("PneumaticaVuoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotti.
        /// </summary>
        public static string Prodotti {
            get {
                return ResourceManager.GetString("Prodotti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotto.
        /// </summary>
        public static string Prodotto {
            get {
                return ResourceManager.GetString("Prodotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotto da clonare.
        /// </summary>
        public static string Prodotto_da_clonare {
            get {
                return ResourceManager.GetString("Prodotto da clonare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prodotto già esistente!.
        /// </summary>
        public static string ProdottoEsistente {
            get {
                return ResourceManager.GetString("ProdottoEsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Robot.
        /// </summary>
        public static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        public static string Salva {
            get {
                return ResourceManager.GetString("Salva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona percorso.
        /// </summary>
        public static string SelezionaPercorso {
            get {
                return ResourceManager.GetString("SelezionaPercorso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona prodotto.
        /// </summary>
        public static string SelezionaProdotto {
            get {
                return ResourceManager.GetString("SelezionaProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare Modalità Operativa.
        /// </summary>
        public static string SelezionareModalitaOperativa {
            get {
                return ResourceManager.GetString("SelezionareModalitaOperativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stampante.
        /// </summary>
        public static string Stampante {
            get {
                return ResourceManager.GetString("Stampante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Storico.
        /// </summary>
        public static string Storico {
            get {
                return ResourceManager.GetString("Storico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il nome utente è obbligatorio.
        /// </summary>
        public static string UsernameRichiesto {
            get {
                return ResourceManager.GetString("UsernameRichiesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utente non trovato.
        /// </summary>
        public static string UtenteAssente {
            get {
                return ResourceManager.GetString("UtenteAssente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vai.
        /// </summary>
        public static string VaiA {
            get {
                return ResourceManager.GetString("VaiA", resourceCulture);
            }
        }
    }
}
